model_name : "Pengi-MSS"
device : "cuda:0"
num_epochs : 1000
save_checkpoint_epoch: 100

# Datasets Configuration
dataset_dir : "./dataset"
batch_size : 64

# Optimizer Configuration
learning_rate : 0.001
weight_decay: 0.00001

# Scheduler Configuration
gradient_clipping : 0.1
warmup_steps_ratio: 0.01
grad_accum_steps: 1

